import clsx from 'clsx'
import { useEffect, useState } from 'react'
import { KTIcon, toAbsoluteUrl } from '../../../_metronic/helpers'
import { getLayoutFromLocalStorage, ILayout, LayoutSetup } from '../../../_metronic/layout/core'
import { ToolbarWrapper } from '../../../_metronic/layout/components/toolbar'
import { useAtom, useAtomValue, useSetAtom } from 'jotai';
import { toolbarTicketsNavigationAtom, toolbarTicketsSearchAtom } from '../../atoms/toolbar-atoms/toolbarTicketsAtom';
import { totalTicketsAtom, fetchedTicketsAtom, isTicketsFetchedAtom, fetchMorePagesFlagAtom, maxIdAtom, ticketsAtom, maxTotalAtom, pinnedTicketsIdsAtom } from '../../atoms/tickets-page-atom/ticketsPageAtom';
import { toolbarTicketsFrontFiltersAtom } from '../../atoms/toolbar-atoms/toolbarTicketsAtom'
import { userAtom } from "../../atoms/auth-atoms/authAtom";

import { PageTitleTickets } from '../../../_metronic/layout/components/toolbar/page-title/PageTitleTickets'
import { GetTicketsViewById } from '../../config/ApiCalls'
import TicketCard from '../../../_metronic/layout/components/custom-components/Card'
import { Content } from '../../../_metronic/layout/components/content'
import { Link, useNavigate, useLocation } from 'react-router-dom'
import { addPinnedTicketId, removePinnedTicketId, getPinnedTicketIds } from '../../../utils/indexDB'

const TicketsPage: React.FC = () => {

  // const currentPage = useAtomValue(toolbarTicketsNavigationAtom)
  const [currentTicketsPage, setCurrentTicketsPage] = useState<number>(1)
  const toolbarSearch = useAtomValue(toolbarTicketsSearchAtom);
  const navigate = useNavigate()
  const location = useLocation();
  // const [ticketsFetched, setTicketsFetched] = useAtom(fetchedTicketsAtom)
  const [tickets, setTickets] = useAtom(ticketsAtom)
  const [frontFilter, setFrontFilter] = useAtom(toolbarTicketsFrontFiltersAtom)

  const [ticketsSearchFiltered, setTicketsSearchFiltered] = useState<any[]>([])

  const setIsTicketsFetch = useSetAtom(isTicketsFetchedAtom)
  const fetchMorePagesFlag = useAtomValue(fetchMorePagesFlagAtom)
  const setFetchMorePagesFlag = useSetAtom(fetchMorePagesFlagAtom)
  const [totalPagesFetched, setTotalPagesFetched] = useState<number>(1)

  const setTotalTickets = useSetAtom(totalTicketsAtom)// Set the total tickets per query of fetched in this instance only
  const [isDataLoading, setIsDataLoading] = useState(true)
  const [maxTotalTickets, setMaxTotalTickets] = useAtom(maxTotalAtom)
  const [paginatedTickets, setPaginatedTickets] = useState<any[]>([])

  const [pinnedTicketIds, setPinnedTicketIds] = useAtom(pinnedTicketsIdsAtom) // State to track pinned ticket IDs
  const [sortedTickets, setSortedTickets] = useState<any[]>([])
  const usrAtom = useAtomValue(userAtom);

  // useEffect(() => {
  //   if (location.state?.from === "details" && ticketsFetched.length > 0) {
  //     console.log("Navigated back from details; skipping fetch");
  //     return;
  //   }
  //   const fetchTickets = async () => {
  //     try {
  //       const response = await GetTicketsViewById(1, '0-100', 'desc')
  //       setTicketsFetched(response.data)
  //       setTotalTickets(response.data.length) // Set the total tickets

  //     } catch (error) {
  //       console.error('Error fetching tickets:', error)
  //     }
  //   }

  //   fetchTickets()
  // }, [])


  const handlePinTicket = async (id: string) => {
    setPinnedTicketIds((prevPinned) => {
      if (prevPinned.includes(id)) {
        removePinnedTicketId(id)
        return prevPinned.filter((ticketId) => ticketId !== id)
      } else {
        addPinnedTicketId(id)
        return [...prevPinned, id]
      }
    })
  }
  const handleStarringTicket = async (id: string) => {
    return
  }
  const x =
    useEffect(() => {
      if (location.state?.from === 'details' && tickets.length > 0) {
        console.log('Navigated back from details; skipping fetch')
        setIsDataLoading(false)

        return
      }
      const fetchTickets = async () => {
        try {
          const response = await GetTicketsViewById('0-5', 'desc')
          const responseData = response.data.data
          setMaxTotalTickets(response.data.totalcount)
          setTickets(responseData)
          setTotalTickets(responseData.length)
          setIsTicketsFetch(true)
          setIsDataLoading(false)

        } catch (error) {
          console.error('Error fetching tickets:', error)
        }
      }

      fetchTickets()
    }, [location.state, setTickets, setTotalTickets, setIsTicketsFetch,])

  const getLowestId = (tickets: any[]) => {
    if (tickets.length === 0) return null
    return Math.min(...tickets.map(ticket => ticket.id))
  }
  useEffect(() => {
    if (fetchMorePagesFlag) {
      const fetchMorePages = async () => {
        try {
          const countOfPages = totalPagesFetched + 1

          const lowestId = getLowestId(tickets)
          if (lowestId !== null) {
            // the error is caused by duplicate objects , so its getting confused
            // const response = await GetTicketsViewById(lowestId-1, '0-3', 'desc')

            const response = await GetTicketsViewById('0-5', 'desc', lowestId)
            const responseData = response.data.data
            if (responseData.length > 0) {
              const updatedTickets = [...tickets, ...responseData];

              setTickets(updatedTickets)
              setTotalTickets(prevTotal => prevTotal + responseData.length)
              setIsDataLoading(false)

            }
            setTotalPagesFetched(countOfPages)
            setFetchMorePagesFlag(false)
          }
        } catch (error) {
          console.error('Error fetching more tickets:', error)
          setFetchMorePagesFlag(false) // Reset the flag in case of error

        }
      }
      setIsDataLoading(true)

      fetchMorePages()
    }
  }, [tickets, fetchMorePagesFlag, totalPagesFetched, setTickets, setTotalTickets, setFetchMorePagesFlag])

  const handleTicketClick = (ticket: any) => {
    navigate(`/ticket/${ticket.id}`, { state: { ticket } })
  }


  const changePriority = (id: number) => {
    console.log(`Change priority for ticket ID: ${id}`)
  }

  const pinTicket = (id: number) => {
    console.log(`Pin ticket ID: ${id}`)
  }

  const replyToTicket = (id: number) => {
    console.log(`Reply to ticket ID: ${id}`)
  }

  const ticketsPerPage = 6 // tickets to show in 1 page

  const updatePaginatedTickets = () => {
    const startIdx = (currentTicketsPage - 1) * ticketsPerPage;
    const endIdx = currentTicketsPage * ticketsPerPage;

    
    if (toolbarSearch.trim()) {
      setPaginatedTickets(ticketsSearchFiltered.slice(startIdx, endIdx)); // Paginate the filtered results
    } else if (frontFilter) {
      setPaginatedTickets(filteredTickets.slice(startIdx, endIdx)); // Paginate the front-filtered results
    } else {
      setPaginatedTickets(tickets.slice(startIdx, endIdx)); // Paginate the full list of tickets
    }
  };
  useEffect(() => {
    updatePaginatedTickets();
  }, [currentTicketsPage, ticketsSearchFiltered, frontFilter]);
  useEffect(() => {
    setCurrentTicketsPage(1);
  }, [toolbarSearch, frontFilter]);
  // const updatePaginatedTickets = () => {
  //   const startIdx = (currentTicketsPage - 1) * ticketsPerPage;
  //   const endIdx = currentTicketsPage * ticketsPerPage;
  //   setPaginatedTickets(filteredTickets.slice(startIdx, endIdx));
  // };
  useEffect(() => {
    updatePaginatedTickets();
  }, [currentTicketsPage, ticketsSearchFiltered, frontFilter]);

  useEffect(() => {
    if (toolbarSearch.trim() === '') {
      setTicketsSearchFiltered(tickets); // Reset to all tickets if search is empty or whitespace
    } else {
      setTicketsSearchFiltered(
        tickets.filter((item) => {
          return Object.values(item)
            .join("")
            .toLowerCase()
            .includes(toolbarSearch.toLowerCase());
        })

      );
    }
  }, [toolbarSearch, tickets]);
  useEffect(() => {
    const sortedTickets = [...tickets].sort((a, b) => {
      if (pinnedTicketIds.includes(a.id) && !pinnedTicketIds.includes(b.id)) {
        return -1
      }
      if (!pinnedTicketIds.includes(a.id) && pinnedTicketIds.includes(b.id)) {
        return 1
      }
      return 0
    })
    const filtered = sortedTickets.filter(ticket => {
      const matchesStatus = frontFilter.status === '' || ticket.status_label === frontFilter.status;
      const matchesUrgency = frontFilter.urgency === '' || ticket.urgency_label === frontFilter.urgency;
      const matchesPriority = frontFilter.priority === '' || ticket.priority_label === frontFilter.priority;
      const matchesType = frontFilter.type === '' || ticket.type_label === frontFilter.type;
      const matchesRequester = frontFilter.requester === '' || ticket.requester === frontFilter.requester;
      const matchesBranch = frontFilter.branch === '' || ticket.area === frontFilter.branch;
      const matchesAssignee = frontFilter.assignee === '' || ticket.users_recipient === frontFilter.assignee;
      return matchesStatus && matchesUrgency && matchesPriority && matchesType && matchesRequester && matchesBranch && matchesAssignee;
    });
    // fix how many pages number is show in tool bar tickets
    // make the pages number to be in footer maybe fixed at end of page
    const paginatedTickets = filtered.slice((currentTicketsPage - 1) * ticketsPerPage, currentTicketsPage * ticketsPerPage)
    setPaginatedTickets(paginatedTickets)
  }, [currentTicketsPage, tickets, pinnedTicketIds, frontFilter])
  const calculateFilteredTickets = () => {
    return tickets.filter((ticket) => {
      const matchesStatus = frontFilter.status === '' || ticket.status_label === frontFilter.status;
      const matchesUrgency = frontFilter.urgency === '' || ticket.urgency_label === frontFilter.urgency;
      const matchesPriority = frontFilter.priority === '' || ticket.priority_label === frontFilter.priority;
      const matchesType = frontFilter.type === '' || ticket.type_label === frontFilter.type;
      const matchesRequester = frontFilter.requester === '' || ticket.requester === frontFilter.requester;
      const matchesBranch = frontFilter.branch === '' || ticket.area === frontFilter.branch;
      const matchesAssignee = frontFilter.assignee === '' || ticket.users_recipient === frontFilter.assignee;
      return matchesStatus && matchesUrgency && matchesPriority && matchesType && matchesRequester && matchesBranch && matchesAssignee;
    });
  };

  const filteredTickets = frontFilter ? calculateFilteredTickets() : tickets;



  const totalPages = Math.ceil(
    toolbarSearch.trim()
      ? ticketsSearchFiltered.length / ticketsPerPage
      : frontFilter
        ? filteredTickets.length / ticketsPerPage
        : tickets.length / ticketsPerPage
  );
  const handleFirstPage = () => setCurrentTicketsPage(1)
  const handlePreviousPage = () => setCurrentTicketsPage(prev => Math.max(prev - 1, 1))
  const handleNextPage = () => setCurrentTicketsPage(prev => Math.min(prev + 1, totalPages))
  const handleLastPage = () => setCurrentTicketsPage(totalPages)
  const handlePageChange = (page: number) => {
    setCurrentTicketsPage(page)
  }
  const minPagesToShow = 8
  const maxPagesToShow = Math.min(totalPages, minPagesToShow)
  const startPage = Math.floor((currentTicketsPage - 1) / minPagesToShow) * minPagesToShow + 1
  const endPage = Math.min(startPage + minPagesToShow - 1, totalPages)
  const xx = 0;
  useEffect(() => {

    const fetchPinnedTicketIds = async () => {
      const pinnedIds = await getPinnedTicketIds()
      setPinnedTicketIds(pinnedIds)
    }
    fetchPinnedTicketIds()
  }, [setPinnedTicketIds])
  const [filteredFrontTickets, setFilteredFrontTickets] = useState<any[]>([])



  useEffect(() => {
    return () => {
      // Reset the filters when the component unmounts
      setFrontFilter({
        status: '',
        urgency: '',
        priority: '',
        type: '',
        requester: '',
        branch: '',
        assignee: ''
      });
    };
  }, [setFrontFilter]);
  const hasActiveFilters = Object.values(frontFilter).some(value => value !== '');

  const demoTickets=[
    {
      id: 74,
      entities_id: 0,
      name: "telecomadmin",
      date: "2025-01-17 13:47:50",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: "2025-01-17 13:47:50",
      date_mod: "2025-01-17 13:47:50",
      users_id_lastupdater: 2,
      users_lastupdater: "cobalt",
      status: 2,
      status_label: "assigned",
      users_id_recipient: 2,
      users_recipient: "cobalt",
      requesttypes_id: 1,
      content: "&#60;p&#62;scdasdsadas&#60;/p&#62;",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 0,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 1,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 8,
      validation_percent: 0,
      date_creation: "2025-01-17 13:47:50",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 73,
      entities_id: 0,
      name: "NewAssigned",
      date: "2025-01-17 13:13:22",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-17 12:13:21",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 1,
      status_label: "new",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "I am testing the ticket",
      urgency: 1,
      urgency_label: "Very low",
      impact: 3,
      impact_label: "Medium",
      priority: 5,
      priority_label: "Very high",
      itilcategories_id: 3,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-17 12:13:21",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 72,
      entities_id: 0,
      name: "asdsafa",
      date: "2025-01-15 12:00:00",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: "2025-01-15 14:27:54",
      date_mod: "2025-01-15 14:27:54",
      users_id_lastupdater: 2,
      users_lastupdater: "cobalt",
      status: 2,
      status_label: "assigned",
      users_id_recipient: 2,
      users_recipient: "cobalt",
      requesttypes_id: 1,
      content: "&#60;p&#62;asdasfas&#60;/p&#62;",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 0,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 8874,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-15 14:27:54",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 71,
      entities_id: 0,
      name: "ewuhfskjdbfjkdsanfsdavsavfb",
      date: "2025-01-10 17:00:47",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: "2025-01-13 15:07:41",
      date_mod: "2025-01-16 21:32:44",
      users_id_lastupdater: 2,
      users_lastupdater: null,
      status: 2,
      status_label: "assigned",
      users_id_recipient: 7,
      users_recipient: null,
      requesttypes_id: 1,
      content: "bgdjnhgfnjg",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 252414,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-10 16:00:46",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 70,
      entities_id: 0,
      name: "testttt",
      date: "2025-01-06 12:00:00",
      closedate: "2025-01-06 12:00:00",
      solvedate: "2025-01-06 12:00:00",
      takeintoaccountdate: null,
      date_mod: "2025-01-10 14:33:32",
      users_id_lastupdater: 16,
      users_lastupdater: "m.harb",
      status: 6,
      status_label: "closed",
      users_id_recipient: 16,
      users_recipient: "m.harb",
      requesttypes_id: 1,
      content: "&#60;p&#62;wrewewfd&#60;/p&#62;",
      urgency: 4,
      urgency_label: "High",
      impact: 2,
      impact_label: "Low",
      priority: 5,
      priority_label: "Very high",
      itilcategories_id: 0,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 1,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-10 14:28:08",
      areas_id: 8,
      area: "Area Tecnica",
      starred: 0,
    },
    {
      id: 69,
      entities_id: 0,
      name: "testttt",
      date: "2025-01-10 15:19:14",
      closedate: "2025-01-10 15:19:14",
      solvedate: "2025-01-10 15:19:14",
      takeintoaccountdate: null,
      date_mod: "2025-01-10 15:14:06",
      users_id_lastupdater: 16,
      users_lastupdater: "m.harb",
      status: 6,
      status_label: "closed",
      users_id_recipient: 16,
      users_recipient: "m.harb",
      requesttypes_id: 1,
      content: "etrtgb",
      urgency: 2,
      urgency_label: "Low",
      impact: 3,
      impact_label: "Medium",
      priority: 1,
      priority_label: "Very low",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-10 14:19:12",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 68,
      entities_id: 0,
      name: "namwww3",
      date: "2025-01-10 14:06:59",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-10 13:55:32",
      users_id_lastupdater: 2,
      users_lastupdater: "cobalt",
      status: 1,
      status_label: "new",
      users_id_recipient: 2,
      users_recipient: "cobalt",
      requesttypes_id: 1,
      content: "eywrgufgsdanbvdsvsavbmav",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 1,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-10 13:16:33",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 67,
      entities_id: 0,
      name: "namwww2",
      date: "2025-01-10 14:06:59",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-10 13:55:24",
      users_id_lastupdater: 2,
      users_lastupdater: "cobalt",
      status: 1,
      status_label: "new",
      users_id_recipient: 2,
      users_recipient: "cobalt",
      requesttypes_id: 1,
      content: "",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 1,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-10 13:15:22",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 66,
      entities_id: 0,
      name: "namwwww",
      date: "2025-01-10 14:06:59",
      closedate: null,
      solvedate: "2025-01-10 15:41:37",
      takeintoaccountdate: "2025-01-10 15:41:37",
      date_mod: "2025-01-10 15:41:37",
      users_id_lastupdater: 16,
      users_lastupdater: null,
      status: 5,
      status_label: "solved",
      users_id_recipient: 7,
      users_recipient: null,
      requesttypes_id: 1,
      content: "",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: "2025-01-10 15:41:37",
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 5678,
      takeintoaccount_delay_stat: 5678,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-10 13:15:19",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 65,
      entities_id: 0,
      name: "namwwww",
      date: "2025-01-10 14:06:59",
      closedate: null,
      solvedate: "2025-01-10 15:43:17",
      takeintoaccountdate: "2025-01-10 15:43:17",
      date_mod: "2025-01-10 15:43:17",
      users_id_lastupdater: 16,
      users_lastupdater: null,
      status: 5,
      status_label: "solved",
      users_id_recipient: 2,
      users_recipient: null,
      requesttypes_id: 1,
      content: "",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: "2025-01-10 15:43:17",
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 5778,
      takeintoaccount_delay_stat: 5778,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-10 13:14:34",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 64,
      entities_id: 0,
      name: "aaa",
      date: "2024-12-25 17:15:00",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-10 12:56:40",
      users_id_lastupdater: 2,
      users_lastupdater: "cobalt",
      status: 1,
      status_label: "new",
      users_id_recipient: 2,
      users_recipient: "cobalt",
      requesttypes_id: 1,
      content: "Ticket Description",
      urgency: 1,
      urgency_label: "Very low",
      impact: 3,
      impact_label: "Medium",
      priority: 4,
      priority_label: "High",
      itilcategories_id: 0,
      type: 3,
      type_label: null,
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-10 12:56:40",
      areas_id: 1,
      area: null,
      starred: 0,
    },
    {
      id: 63,
      entities_id: 0,
      name: "test109",
      date: "2025-01-09 17:44:14",
      closedate: "2025-01-09 21:22:54",
      solvedate: "2025-01-09 21:22:54",
      takeintoaccountdate: "2025-01-09 21:21:21",
      date_mod: "2025-01-09 21:22:54",
      users_id_lastupdater: 2,
      users_lastupdater: null,
      status: 6,
      status_label: "closed",
      users_id_recipient: 7,
      users_recipient: null,
      requesttypes_id: 1,
      content: "",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 13120,
      solve_delay_stat: 13120,
      takeintoaccount_delay_stat: 13027,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-09 16:44:13",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 62,
      entities_id: 0,
      name: "tguyhjhjvbhsdbvldshbv",
      date: "2025-01-09 17:39:06",
      closedate: "2025-01-10 15:43:36",
      solvedate: "2025-01-10 15:43:36",
      takeintoaccountdate: "2025-01-10 15:43:36",
      date_mod: "2025-01-10 15:43:36",
      users_id_lastupdater: 16,
      users_lastupdater: null,
      status: 6,
      status_label: "closed",
      users_id_recipient: 7,
      users_recipient: null,
      requesttypes_id: 1,
      content: "",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 79470,
      solve_delay_stat: 79470,
      takeintoaccount_delay_stat: 79470,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-09 16:39:05",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 61,
      entities_id: 0,
      name: "ytrew",
      date: "2025-01-09 17:35:01",
      closedate: "2025-01-09 21:23:11",
      solvedate: "2025-01-09 21:23:11",
      takeintoaccountdate: "2025-01-09 21:23:11",
      date_mod: "2025-01-09 21:23:11",
      users_id_lastupdater: 2,
      users_lastupdater: null,
      status: 6,
      status_label: "closed",
      users_id_recipient: 7,
      users_recipient: null,
      requesttypes_id: 1,
      content: "",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 13690,
      solve_delay_stat: 13690,
      takeintoaccount_delay_stat: 13690,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-09 16:35:01",
      areas_id: 1,
      area: null,
      starred: 0,
    },
    {
      id: 60,
      entities_id: 0,
      name: "tckttt",
      date: "2025-01-09 17:02:35",
      closedate: null,
      solvedate: "2025-01-20 06:46:56",
      takeintoaccountdate: "2025-01-20 06:46:41",
      date_mod: "2025-01-20 06:46:56",
      users_id_lastupdater: 2,
      users_lastupdater: null,
      status: 5,
      status_label: "solved",
      users_id_recipient: 7,
      users_recipient: null,
      requesttypes_id: 1,
      content: "",
      urgency: 2,
      urgency_label: "Low",
      impact: 3,
      impact_label: "Medium",
      priority: 1,
      priority_label: "Very low",
      itilcategories_id: 3,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: "2025-01-20 06:46:56",
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 913461,
      takeintoaccount_delay_stat: 913446,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-09 16:02:35",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 59,
      entities_id: 0,
      name: "tckt80",
      date: "2025-01-09 16:37:02",
      closedate: "2025-01-10 15:13:34",
      solvedate: "2025-01-10 15:13:34",
      takeintoaccountdate: "2025-01-10 15:13:34",
      date_mod: "2025-01-10 15:13:34",
      users_id_lastupdater: 16,
      users_lastupdater: null,
      status: 6,
      status_label: "closed",
      users_id_recipient: 7,
      users_recipient: null,
      requesttypes_id: 1,
      content: "",
      urgency: 2,
      urgency_label: "Low",
      impact: 3,
      impact_label: "Medium",
      priority: 5,
      priority_label: "Very high",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 81392,
      solve_delay_stat: 81392,
      takeintoaccount_delay_stat: 81392,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-09 15:37:03",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 58,
      entities_id: 0,
      name: "ticketing",
      date: "2025-01-09 16:25:01",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-09 15:25:01",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 1,
      status_label: "new",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 5,
      urgency_label: "Very high",
      impact: 3,
      impact_label: "Medium",
      priority: 2,
      priority_label: "Low",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-09 15:25:01",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 57,
      entities_id: 0,
      name: "test87",
      date: "2025-01-09 16:21:27",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-09 15:21:27",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 1,
      status_label: "new",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 5,
      urgency_label: "Very high",
      impact: 3,
      impact_label: "Medium",
      priority: 1,
      priority_label: "Very low",
      itilcategories_id: 3,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-09 15:21:27",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 56,
      entities_id: 0,
      name: "System Check",
      date: "2025-01-09 09:36:39",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: "2025-01-09 09:36:39",
      date_mod: "2025-01-09 09:36:39",
      users_id_lastupdater: 2,
      users_lastupdater: "cobalt",
      status: 2,
      status_label: "assigned",
      users_id_recipient: 2,
      users_recipient: "cobalt",
      requesttypes_id: 1,
      content: "&#60;p&#62;Hi everyone this is a test message&#60;/p&#62;",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 0,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 1,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-09 09:36:39",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 55,
      entities_id: 0,
      name: "ridaaaaa",
      date: "2025-01-08 16:41:41",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-08 15:41:47",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 1,
      status_label: "new",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 1,
      priority_label: "Very low",
      itilcategories_id: 3,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-08 15:41:47",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 54,
      entities_id: 0,
      name: "test345",
      date: "2025-01-07 15:46:11",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-07 14:46:11",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 1,
      status_label: "new",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 1,
      priority_label: "Very low",
      itilcategories_id: 3,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-07 14:46:11",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 53,
      entities_id: 0,
      name: "test203",
      date: "2025-01-07 10:59:27",
      closedate: "2025-01-10 12:46:59",
      solvedate: "2025-01-10 12:46:59",
      takeintoaccountdate: null,
      date_mod: "2025-01-10 12:46:59",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 6,
      status_label: "closed",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 4,
      urgency_label: "High",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 265652,
      solve_delay_stat: 265652,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-07 09:59:28",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 52,
      entities_id: 0,
      name: "test201",
      date: "2025-01-07 09:47:23",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-07 08:47:23",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 1,
      status_label: "new",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 5,
      urgency_label: "Very high",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-07 08:47:23",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 51,
      entities_id: 0,
      name: "(*&#38;^%$",
      date: "2025-01-07 09:34:37",
      closedate: null,
      solvedate: "2025-01-07 09:34:37",
      takeintoaccountdate: null,
      date_mod: "2025-01-07 08:34:37",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 5,
      status_label: "solved",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 1,
      urgency_label: "Very low",
      impact: 3,
      impact_label: "Medium",
      priority: 2,
      priority_label: "Low",
      itilcategories_id: 3,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-07 08:34:37",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 50,
      entities_id: 0,
      name: "!@#$%",
      date: "2025-01-07 09:31:07",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-07 08:31:08",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 1,
      status_label: "new",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 5,
      urgency_label: "Very high",
      impact: 3,
      impact_label: "Medium",
      priority: 4,
      priority_label: "High",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-07 08:31:08",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 49,
      entities_id: 0,
      name: "testttt",
      date: "2025-01-07 09:25:45",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-07 08:25:46",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 1,
      status_label: "new",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 5,
      urgency_label: "Very high",
      impact: 3,
      impact_label: "Medium",
      priority: 4,
      priority_label: "High",
      itilcategories_id: 3,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-07 08:25:46",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 48,
      entities_id: 0,
      name: "wwww",
      date: "2025-01-06 14:40:17",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-06 13:40:10",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 1,
      status_label: "new",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 5,
      urgency_label: "Very high",
      impact: 3,
      impact_label: "Medium",
      priority: 4,
      priority_label: "High",
      itilcategories_id: 3,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-06 13:40:10",
      areas_id: 0,
      area: null,
      starred: 0,
    },
    {
      id: 47,
      entities_id: 0,
      name: "testdate",
      date: "2025-01-06 14:07:08",
      closedate: "2025-01-10 13:55:58",
      solvedate: "2025-01-10 13:55:58",
      takeintoaccountdate: null,
      date_mod: "2025-01-10 13:55:58",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 6,
      status_label: "closed",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 344930,
      solve_delay_stat: 344930,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-06 13:07:02",
      areas_id: 1,
      area: null,
      starred: 0,
    },
    {
      id: 46,
      entities_id: 0,
      name: "qwertyuio",
      date: "2025-01-02 14:21:48",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: "2025-01-03 13:58:25",
      date_mod: "2025-01-10 13:57:10",
      users_id_lastupdater: 2,
      users_lastupdater: null,
      status: 3,
      status_label: "plan",
      users_id_recipient: 7,
      users_recipient: null,
      requesttypes_id: 1,
      content: "",
      urgency: 5,
      urgency_label: "Very high",
      impact: 3,
      impact_label: "Medium",
      priority: 4,
      priority_label: "High",
      itilcategories_id: 3,
      type: 2,
      type_label: "Demand",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 84997,
      actiontime: 0,
      is_deleted: 1,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-02 13:21:49",
      areas_id: 8,
      area: "Area Tecnica",
      starred: 0,
    },
    {
      id: 45,
      entities_id: 0,
      name: "harb",
      date: "2025-01-02 14:15:27",
      closedate: null,
      solvedate: null,
      takeintoaccountdate: null,
      date_mod: "2025-01-02 13:15:27",
      users_id_lastupdater: 7,
      users_lastupdater: "m.hareb",
      status: 3,
      status_label: "plan",
      users_id_recipient: 7,
      users_recipient: "m.hareb",
      requesttypes_id: 1,
      content: "",
      urgency: 3,
      urgency_label: "Medium",
      impact: 3,
      impact_label: "Medium",
      priority: 3,
      priority_label: "Medium",
      itilcategories_id: 3,
      type: 1,
      type_label: "Incident",
      global_validation: 1,
      slas_id_ttr: 0,
      slas_id_tto: 0,
      slalevels_id_ttr: 0,
      time_to_resolve: null,
      time_to_own: null,
      begin_waiting_date: null,
      sla_waiting_duration: 0,
      ola_waiting_duration: 0,
      olas_id_tto: 0,
      olas_id_ttr: 0,
      olalevels_id_ttr: 0,
      ola_tto_begin_date: null,
      ola_ttr_begin_date: null,
      internal_time_to_resolve: null,
      internal_time_to_own: null,
      waiting_duration: 0,
      close_delay_stat: 0,
      solve_delay_stat: 0,
      takeintoaccount_delay_stat: 0,
      actiontime: 0,
      is_deleted: 0,
      locations_id: 0,
      validation_percent: 0,
      date_creation: "2025-01-02 13:15:27",
      areas_id: 1,
      area: null,
      starred: 0,
    },
  ]
  return (
    <>
      {/* <PageTitleTickets>{(toolbarSearch && toolbarSearch.trim() !== '') ? 'Filtered Tickets' : 'Tickets'}</PageTitleTickets> */}
      <ToolbarWrapper source={"tickets"} />
      <Content>
        <div className='tickets-component-container align-self-stretch'>
          <div className="d-flex flex-column justify-content-between">
            {isDataLoading ? (
              <div className="spinner-wrapper">
                <div className="spinner-border spinner-loading-data" role="status">
                  <span className="visually-hidden">Loading...</span>
                </div>
              </div>
            ) : (
              (paginatedTickets).map(ticket => (
                <TicketCard
                  key={ticket.id}
                  id={ticket.id}
                  status={ticket.status_label}
                  date={ticket.date}
                  title={ticket.name}
                  description={ticket.content || "Lorem Ipsum is simply dummy text of the printing and typesetting industry."}
                  assignedTo={{ name: ticket.users_recipient, avatar: "person-bounding-box" }} // Placeholder avatar
                  raisedBy={{ name: ticket.users_lastupdater, initials: ticket?.users_lastupdater?.charAt(0) }}
                  priority={ticket.priority_label}
                  category={ticket.type_label}
                  lastUpdate={ticket.date_mod}
                  onClick={() => handleTicketClick(ticket)} // Add onClick handler
                  onPin={handlePinTicket} // Pass the handlePinTicket function
                  isPinned={pinnedTicketIds.includes(ticket.id)} // Pass the pinned status
                  isStarred={ticket.starred} // Pass the pinned status
                  onStarred={handleStarringTicket} // Pass the handlePinTicket function

                />
              ))
            )}


          </div>

        </div>
      </Content>
      <div className=" tickets-pagination-controls">
            <button className='btn btn-sm btn-light me-2' onClick={handleFirstPage} disabled={currentTicketsPage === 1}>First</button>
            <button className='btn btn-sm btn-light me-2' onClick={handlePreviousPage} disabled={currentTicketsPage === 1}>Previous</button>
            {Array.from({ length: endPage - startPage + 1 }, (_, index) => startPage + index).map(page => (
              <button
                key={page}
                className={clsx('btn btn-sm me-2', { 'btn-primary': currentTicketsPage === page, 'btn-light': currentTicketsPage !== page })}
                onClick={() => handlePageChange(page)}
              >
                {page}
              </button>
            ))}
            <button className='btn btn-sm btn-light me-2' onClick={handleNextPage} disabled={currentTicketsPage === totalPages}>Next</button>
            <button className='btn btn-sm btn-light' onClick={handleLastPage} disabled={currentTicketsPage === totalPages}>Last</button>
          </div>
      {/* <TicketCard
          id="#HFCS00117299"
          date ="01-10-2024"
          status="CANCELED"
          title="Problem upgrading account to a premium plan?"
          description="Our team is finding it difficult to upgrade from a free plan to a premium plan."
          assignedTo={{ name: "William Haug", avatar: "https://via.placeholder.com/40" }}
          raisedBy={{ name: "Break Rick", initials: "BR" }}
          priority="CRITICAL"
          category="Acme Support"
        /> */}
    </>
  )
}

export { TicketsPage }
