version: '3'
services:
  react-ui:
    container_name: react-itsm-ui
    build:
      context: .
      args:
        IMAGE_TAG: ${TAG}
    image: react-itsm-image:${TAG}
    network_mode: host
    restart: unless-stopped
    env_file:
      - /home/glpi/main/.env
    environment:
      - PORT=3033