version: '3'
services:
  react-ui:
    container_name: react-itsm-ui
    build:
      context: .
      args:
        IMAGE_TAG: ${TAG} # Dynamically passed from GitHub Actions
    image: react_test:${TAG} # Set the dynamic tag for the image
    ports:
      - "3001:80"
    restart: unless-stopped