version: '3.8'
services:
  react-ui:
    container_name: react-ui
    build:
      context: .
      args:
        IMAGE_TAG: ${TAG} # Dynamically passed from GitHub Actions
    image: react_test:${TAG} # Set the dynamic tag for the image
    ports:
      - "3001:3000"
    restart: unless-stopped
    env_file: 
      - /home/hlpi/main/.env # Include the .env file

# version: '3'
# services:
#   react-ui:
#     container_name: react-itsm-ui
#     build:
#       context: .
#     image: react-itsm-image
#     volumes:git
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - "3001:3000"
#     restart: unless-stopped