export type ErrorResponse = {
  response?: {
    data?: any;
  };
};

export type UserAtomType = {
  session_token: string;
  session: {
    valid_id: string;
    glpi_currenttime: string;
    glpi_use_mode: number;
    glpiis_ids_visible: string;
    glpifriendlyname: string;
    glpiname: string;
    glpirealname: string;
    glpifirstname: string;
    glpidefault_entity: number;
    glpiextauth: number;
    glpiauthtype: number;
    glpiroot: string;
    glpi_plannings: any[];
    glpicrontimer: number;
    glpi_tabs: any[];
    glpibackcreated: string;
    glpicsv_delimiter: string;
    glpidate_format: number;
    glpidefault_requesttypes_id: string;
    glpidisplay_count_on_home: string;
    glpiduedatecritical_color: string;
    glpiduedatecritical_less: string;
    glpiduedatecritical_unit: string;
    glpiduedateok_color: string;
    glpiduedatewarning_color: string;
    glpiduedatewarning_less: string;
    glpiduedatewarning_unit: string;
    glpifollowup_private: string;
    glpikeep_devices_when_purging_item: string;
    glpilanguage: string;
    glpilist_limit: string;
    glpilock_autolock_mode: string;
    glpilock_directunlock_notification: string;
    glpinames_format: string;
    glpinotification_to_myself: string;
    glpinumber_format: string;
    glpipdffont: string;
    glpipriority_1: string;
    glpipriority_2: string;
    glpipriority_3: string;
    glpipriority_4: string;
    glpipriority_5: string;
    glpipriority_6: string;
    glpirefresh_views: string;
    glpiset_default_tech: string;
    glpiset_default_requester: string;
    glpishow_count_on_tabs: string;
    glpishow_jobs_at_login: string;
    glpitask_private: string;
    glpitask_state: string;
    glpiuse_flat_dropdowntree: string;
    glpiuse_flat_dropdowntree_on_search_result: string;
    glpipalette: string;
    glpipage_layout: string;
    glpihighcontrast_css: string;
    glpidefault_dashboard_central: string;
    glpidefault_dashboard_assets: string;
    glpidefault_dashboard_helpdesk: string;
    glpidefault_dashboard_mini_ticket: string;
    glpidefault_central_tab: string;
    glpifold_menu: string;
    glpifold_search: string;
    glpisavedsearches_pinned: string;
    glpirichtext_layout: string;
    glpitimeline_order: string;
    glpiitil_layout: string;
    glpitimeline_action_btn_layout: string;
    glpitimeline_date_format: string;
    glpi_dropdowntranslations: any[];
    glpipluralnumber: number;
    glpiprofiles: {
      name: string;
      entities: {
        id: number;
        name: string;
        is_recursive: number;
      }[];
    };
    glpiactiveprofile: {
      id: number;
      name: string;
      interface: string;
      is_default: number;
      helpdesk_hardware: number;
      helpdesk_item_type: string[];
      ticket_status: any[];
      date_mod: string;
      comment: string;
      problem_status: any[];
      create_ticket_on_login: number;
      tickettemplates_id: number;
      changetemplates_id: number;
      problemtemplates_id: number;
      change_status: string | null;
      managed_domainrecordtypes: number[];
      date_creation: string | null;
      agent: number;
      anti_theft: number;
      appliance: number;
      backup: number;
      bookmark_public: number;
      budget: number;
      cable_management: number;
      calendar: number;
      cartridge: number;
      certificate: number;
      change: number;
      changevalidation: number;
      cluster: number;
      co_reach: number;
      computer: number;
      config: number;
      consumable: number;
      contact_enterprise: number;
      contract: number;
      dashboard: number;
      database: number;
      datacenter: number;
      device: number;
      devicesimcard_pinpuk: number;
      document: number;
      domain: number;
      dropdown: number;
      entity: number;
      externalevent: number;
      followup: number;
      global_validation: number;
      group: number;
      infocom: number;
      internet: number;
      inventory: number;
      itilcategory: number;
      itilfollowuptemplate: number;
      itiltemplate: number;
      knowbase: number;
      knowbasecategory: number;
      license: number;
      line: number;
      lineoperator: number;
      link: number;
      location: number;
      locked_field: number;
      logs: number;
      monitor: number;
      networking: number;
      notification: number;
      password_update: number;
      pendingreason: number;
      peripheral: number;
      personalization: number;
      phone: number;
      planning: number;
      plugin_antitheft: number;
      printer: number;
      problem: number;
      profile: number;
      project: number;
      projecttask: number;
      queuednotification: number;
      recurrentchange: number;
      refusedequipment: number;
      reminder_public: number;
      reports: number;
      reservation: number;
      rssfeed_public: number;
      rule_asset: number;
      rule_dictionnary_dropdown: number;
      rule_dictionnary_printer: number;
      rule_dictionnary_software: number;
      rule_import: number;
      rule_ldap: number;
      rule_location: number;
      rule_mailcollector: number;
      rule_softwarecategories: number;
      rule_ticket: number;
      search_config: number;
      show_group_hardware: number;
      slm: number;
      snmpcredential: number;
      software: number;
      solutiontemplate: number;
      state: number;
      statistic: number;
      system_logs: number;
      task: number;
      taskcategory: number;
      ticket: number;
      ticketcost: number;
      ticketrecurrent: number;
      ticketvalidation: number;
      transfer: number;
      typedoc: number;
      unmanaged: number;
      user: number;
      entities: any[];
    };
    glpiactiveentities: number[];
    glpisearch: any[];
    glpiactiveentities_string: string;
    glpiparententities: any[];
    glpiparententities_string: string;
    glpiactive_entity: number;
    glpiactive_entity_recursive: number;
    glpiactive_entity_name: string;
    glpiactive_entity_shortname: string;
    glpishowallentities: number;
    glpigroups: any[];
  };
};

export const initialUserState: UserAtomType = {
  session_token: "",
  session: {
    valid_id: "",
    glpi_currenttime: "",
    glpi_use_mode: 0,
    glpiis_ids_visible: "",
    glpifriendlyname: "",
    glpiname: "",
    glpirealname: "",
    glpifirstname: "",
    glpidefault_entity: 0,
    glpiextauth: 0,
    glpiauthtype: 0,
    glpiroot: "",
    glpi_plannings: [],
    glpicrontimer: 0,
    glpi_tabs: [],
    glpibackcreated: "",
    glpicsv_delimiter: "",
    glpidate_format: 0,
    glpidefault_requesttypes_id: "",
    glpidisplay_count_on_home: "",
    glpiduedatecritical_color: "",
    glpiduedatecritical_less: "",
    glpiduedatecritical_unit: "",
    glpiduedateok_color: "",
    glpiduedatewarning_color: "",
    glpiduedatewarning_less: "",
    glpiduedatewarning_unit: "",
    glpifollowup_private: "",
    glpikeep_devices_when_purging_item: "",
    glpilanguage: "",
    glpilist_limit: "",
    glpilock_autolock_mode: "",
    glpilock_directunlock_notification: "",
    glpinames_format: "",
    glpinotification_to_myself: "",
    glpinumber_format: "",
    glpipdffont: "",
    glpipriority_1: "",
    glpipriority_2: "",
    glpipriority_3: "",
    glpipriority_4: "",
    glpipriority_5: "",
    glpipriority_6: "",
    glpirefresh_views: "",
    glpiset_default_tech: "",
    glpiset_default_requester: "",
    glpishow_count_on_tabs: "",
    glpishow_jobs_at_login: "",
    glpitask_private: "",
    glpitask_state: "",
    glpiuse_flat_dropdowntree: "",
    glpiuse_flat_dropdowntree_on_search_result: "",
    glpipalette: "",
    glpipage_layout: "",
    glpihighcontrast_css: "",
    glpidefault_dashboard_central: "",
    glpidefault_dashboard_assets: "",
    glpidefault_dashboard_helpdesk: "",
    glpidefault_dashboard_mini_ticket: "",
    glpidefault_central_tab: "",
    glpifold_menu: "",
    glpifold_search: "",
    glpisavedsearches_pinned: "",
    glpirichtext_layout: "",
    glpitimeline_order: "",
    glpiitil_layout: "",
    glpitimeline_action_btn_layout: "",
    glpitimeline_date_format: "",
    glpi_dropdowntranslations: [],
    glpipluralnumber: 0,
    glpiprofiles: {
      name: "",
      entities: [],
    },
    glpiactiveprofile: {
      id: 0,
      name: "",
      interface: "",
      is_default: 0,
      helpdesk_hardware: 0,
      helpdesk_item_type: [],
      ticket_status: [],
      date_mod: "",
      comment: "",
      problem_status: [],
      create_ticket_on_login: 0,
      tickettemplates_id: 0,
      changetemplates_id: 0,
      problemtemplates_id: 0,
      change_status: null,
      managed_domainrecordtypes: [],
      date_creation: null,
      agent: 0,
      anti_theft: 0,
      appliance: 0,
      backup: 0,
      bookmark_public: 0,
      budget: 0,
      cable_management: 0,
      calendar: 0,
      cartridge: 0,
      certificate: 0,
      change: 0,
      changevalidation: 0,
      cluster: 0,
      co_reach: 0,
      computer: 0,
      config: 0,
      consumable: 0,
      contact_enterprise: 0,
      contract: 0,
      dashboard: 0,
      database: 0,
      datacenter: 0,
      device: 0,
      devicesimcard_pinpuk: 0,
      document: 0,
      domain: 0,
      dropdown: 0,
      entity: 0,
      externalevent: 0,
      followup: 0,
      global_validation: 0,
      group: 0,
      infocom: 0,
      internet: 0,
      inventory: 0,
      itilcategory: 0,
      itilfollowuptemplate: 0,
      itiltemplate: 0,
      knowbase: 0,
      knowbasecategory: 0,
      license: 0,
      line: 0,
      lineoperator: 0,
      link: 0,
      location: 0,
      locked_field: 0,
      logs: 0,
      monitor: 0,
      networking: 0,
      notification: 0,
      password_update: 0,
      pendingreason: 0,
      peripheral: 0,
      personalization: 0,
      phone: 0,
      planning: 0,
      plugin_antitheft: 0,
      printer: 0,
      problem: 0,
      profile: 0,
      project: 0,
      projecttask: 0,
      queuednotification: 0,
      recurrentchange: 0,
      refusedequipment: 0,
      reminder_public: 0,
      reports: 0,
      reservation: 0,
      rssfeed_public: 0,
      rule_asset: 0,
      rule_dictionnary_dropdown: 0,
      rule_dictionnary_printer: 0,
      rule_dictionnary_software: 0,
      rule_import: 0,
      rule_ldap: 0,
      rule_location: 0,
      rule_mailcollector: 0,
      rule_softwarecategories: 0,
      rule_ticket: 0,
      search_config: 0,
      show_group_hardware: 0,
      slm: 0,
      snmpcredential: 0,
      software: 0,
      solutiontemplate: 0,
      state: 0,
      statistic: 0,
      system_logs: 0,
      task: 0,
      taskcategory: 0,
      ticket: 0,
      ticketcost: 0,
      ticketrecurrent: 0,
      ticketvalidation: 0,
      transfer: 0,
      typedoc: 0,
      unmanaged: 0,
      user: 0,
      entities: [],
    },
    glpiactiveentities: [],
    glpisearch: [],
    glpiactiveentities_string: "",
    glpiparententities: [],
    glpiparententities_string: "",
    glpiactive_entity: 0,
    glpiactive_entity_recursive: 0,
    glpiactive_entity_name: "",
    glpiactive_entity_shortname: "",
    glpishowallentities: 0,
    glpigroups: [],
  },
};
