name: Deploy Main Docker on Release Tag from Specific Branch

on:
  release:
    types:
      - published # Trigger on release creation

jobs:
  deploy:
    if: github.event.release.target_commitish == 'main' # Replace 'main' with your branch name
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Main application
        run: |
          IMAGE_NAME=itsm_front_main
          CONTAINER_NAME=itsm_front_main
          
          # Stop and remove the old container
          docker ps -a -q --filter "name=$CONTAINER_NAME" | xargs -r docker rm -f

          # Remove older images beyond the retention limit (keep 3 older + current)
          docker images $IMAGE_NAME --format "{{.Repository}}:{{.Tag}} {{.CreatedAt}}" | \
          sort -rk 2 | \
          awk 'NR>1 {print $1}' | xargs -r docker rmi -f

          export TAG=${GITHUB_REF_NAME}
          TAG=${GITHUB_REF_NAME} docker compose build
          TAG=${GITHUB_REF_NAME} docker compose up -d --force-recreate
        env:
          GITHUB_REF_NAME: ${{ github.event.release.tag_name }}
