name: Deploy Development Code to Remote Server

on:
  push:
    branches:
      - development  # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner on the same machine

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy Application
      run: |
        mkdir -p /home/glpi/development
        rsync -avz --exclude='.git/' ./ /home/glpi/development/